name: goreleaser-release

on:
  push:
    branches: ["jose/issue-25"]

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        go: ["1.20"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go mod download

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v5
      #   with:
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=publish --snapshot --clean

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: hey
          release_name: Release hey
          body: Release of version hey
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}
