name: goreleaser-release

on:
  push:
    branches: ["jose/issue-25"]

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        go: ["1.20"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go mod download

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v5
      #   with:
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}

      - name: Get the version from GoReleaser
        id: get_version
        run: echo "::set-output name=version::$(goreleaser release --skip-publish --snapshot --rm-dist | grep 'Version' | cut -d ' ' -f 2)"

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: Release of version ${{ steps.get_version.outputs.version }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}
